describe("validation of parameters", {
  test_that("validation of parameters", {
    expect_error(validate_prodnormal_params(mu.x = "a", mu.y = 1, se.x = 1, se.y = 1, rho = 0, n.mc = 100), "Argument mu.x must be numeric!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = "a", se.x = 1, se.y = 1, rho = 0, n.mc = 100), "Argument mu.y must be numeric!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = "a", se.y = 1, rho = 0, n.mc = 100), "Argument se.x must be numeric!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = "a", rho = 0, n.mc = 100), "Argument se.y must be numeric!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = 1, rho = "a", n.mc = 100), "Argument rho  must be numeric!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = 1, rho = 2, n.mc = 100), "rho must be between -1 and 1!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = 1, rho = 0, n.mc = 100, alpha = "a"), "Argument alpha  must be numeric!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = 1, rho = 0, n.mc = 100, alpha = 2), "alpha must be between 0 and 1!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = 1, rho = 0, n.mc = 100, p = "a"), "Argument p must be numeric!")
    expect_error(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = 1, rho = 0, n.mc = 100, p = 2), "p must be between 0 and 1!")
    expect_equal(validate_prodnormal_params(mu.x = 1, mu.y = 1, se.x = 1, se.y = 1, rho = 0, n.mc = NULL), 1e5)
  })
})
